"""initial tables

Revision ID: b03ec0471c15
Revises: 
Create Date: 2025-06-10 16:18:44.328012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03ec0471c15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dwellers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_guys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('establishment', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('dweller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dweller_id'], ['dwellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name_user', sa.String(), nullable=True),
    sa.Column('dweller', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dweller'], ['dwellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubers')
    op.drop_table('delivery_guys')
    op.drop_table('dwellers')
    # ### end Alembic commands ###
